  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: motor_01_joint
    pid: {p: 20.0, i: 0.0, d: 1.0}

  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: motor_02_joint
    pid: {p: 70.0, i: 0.0, d: 1.5}

  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: motor_03_joint
    pid: {p: 40.0, i: 0.0, d: 1.0}
    
  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: motor_04_joint
    pid: {p: 20.0, i: 0.0, d: 0.0} 

  joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: motor_05_joint
    pid: {p: 1.0, i: 0.0, d: 0.1} 

  joint6_position_controller:
    type: effort_controllers/JointPositionController
    joint: gimbal_axle_joint
    pid: {p: 5.0, i: 0.1, d: 0.1} 

  joint7_position_controller:
    type: effort_controllers/JointPositionController
    joint: sensor_housing_joint
    pid: {p: 10.0, i: 0.1, d: 0.1} 
