investigator_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - motor_01_joint
    - motor_02_joint
    - motor_03_joint
    - motor_04_joint
    - motor_05_joint
  gains:
    motor_01_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    motor_02_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    motor_03_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    motor_04_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    motor_05_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
Explorer_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - gimbal_axle_joint
    - sensor_housing_joint
  gains:
    gimbal_axle_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    sensor_housing_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1