investigator_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - motor_01_joint
    - motor_02_joint
    - motor_03_joint
    - motor_04_joint
    - motor_05_joint

  constraints:
      # goal_time: 0.6
      # vel_tolerance is 0 for due to the movegroup/follow_joint_trajectory/goal tolerance is empty
      stopped_velocity_tolerance: 0

  gains:
    motor_01_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    motor_02_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    motor_03_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    motor_04_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    motor_05_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
Explorer_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - gimbal_axle_joint
    - sensor_housing_joint

  constraints:
      # goal_time: 0.6
      # vel_tolerance is 0 for due to the movegroup/follow_joint_trajectory/goal tolerance is empty
      stopped_velocity_tolerance: 0

  gains:
    gimbal_axle_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    sensor_housing_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1